site_name: Mapa L.I.L.A.S
site_description: Documentação do projeto, com os nossos estudos, conteúdos de Sprints, e tudo mais que for relevante para o projeto.
theme:
  name: material
  custom_dir: overrides

  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  - Arquitetura:
      - Arquitetura Técnica: Arquitetura/Arquitetura_Tecnica.md

  - Requisitos:
      - Visão geral: Requisitos/Visão de produto.md
      - Critérios de Aceitação: Requisitos/Criterios de aceitacao.md

  - ATAS Reunião:
      - Reunião01: ATAS Reunião/Ata26_03.md
      - Reunião02: ATAS Reunião/Ata30_03.md
      - Reunião03: ATAS Reunião/ATA reunião15_04.md
      - Reunião04: ATAS Reunião/Ata29_04.md
      - Reunião05: ATAS Reunião/Ata06_05.md
      - Reunião06: ATAS Reunião/Ata13_05.md

  - Estudos:
      - Sprint 00:
          - Arquitetura de Software: Estudos/Sprint00/arquiteturaSoftware.md
          - Requisitos de Software: Estudos/Sprint00/Estudo_Requisitos_de_software.md
          - Git Cheat Sheet: Estudos/Sprint00/git-cheat-sheet.md
          - Guia Rápido Git/GitHub: Estudos/Sprint00/GuiaRapido_GitGitHub.md
          - Metodologias Ágeis: Estudos/Sprint00/_Metodologias.Ageis.md
      - Sprint 01:
          - Docker: Estudos/Sprint01/Docker.md
      - Sprint 02:
          - PostgreSQL: Estudos/Sprint02/postgreSQL.md
          - Protótipo Figma: Estudos/Sprint02/prototipoFigma.md
      - Sprint 03:
          - Persona: Estudos/Sprint03/persona.md
      - Sprint 04:
          - Estudo API Câmara/Senado: "Estudos/Sprint04/Estudo API da Câmara do Senado.md"
          - Pesquisa Legislativa: "Estudos/Sprint04/Pesquisa Legislativa - Monitoramento de PLs (API do Senado).md"
          - Story Map Figma: Estudos/Sprint04/StoryMap-figma.md
          - Wireframe: Estudos/Sprint04/Wireframe.md

  - Métricas de Produtividade:
      - Dashboard: scrum/index.html
