FROM python:3.11-slim
WORKDIR /app

# Dependências de sistema para o PostgreSQL
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Cache de dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o código do backend
COPY . .

# Variável para o Python não criar arquivos .pyc e exibir logs em tempo real
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

# Garante que o entrypoint seja executável
RUN chmod +x entrypoint.sh

# Roda migrations e depois sobe o servidor
ENTRYPOINT ["./entrypoint.sh"]