"""criando_tabelas_iniciais

Revision ID: dea7511548f5
Revises: 
Create Date: 2026-05-16 13:45:37.705846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects import postgresql

revision: str = 'dea7511548f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parlamentares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('casa', sa.String(), nullable=False),
    sa.Column('nome_eleitoral', sa.String(), nullable=False),
    sa.Column('nome_civil', sa.String(), nullable=True),
    sa.Column('sigla_partido', sa.String(), nullable=False),
    sa.Column('sigla_uf', sa.String(length=2), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('url_foto', sa.String(), nullable=True),
    sa.Column('status_mandato', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("casa IN ('Câmara', 'Senado')", name='ck_parlamentares_casa'),
    sa.CheckConstraint("sexo IN ('F', 'M')", name='ck_parlamentares_sexo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pls_camara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('sigla_tipo', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('data_apresentacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('descricao_tipo', sa.String(), nullable=True),
    sa.Column('descricao_situacao', sa.String(), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('dados_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pls_senado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_materia', sa.Integer(), nullable=False),
    sa.Column('identificacao', sa.String(), nullable=False),
    sa.Column('data_apresentacao', sa.Date(), nullable=True),
    sa.Column('data_deliberacao', sa.Date(), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('tramitando', sa.Boolean(), nullable=True),
    sa.Column('sigla_tipo_deliberacao', sa.String(), nullable=True),
    sa.Column('dados_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autoria_camara',
    sa.Column('id_pl', sa.Integer(), nullable=False),
    sa.Column('id_parlamentar', sa.String(), nullable=False),
    sa.Column('tipo_autoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_parlamentar'], ['parlamentares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pl'], ['pls_camara.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pl', 'id_parlamentar')
    )
    op.create_table('autoria_senado',
    sa.Column('id_pl', sa.Integer(), nullable=False),
    sa.Column('id_parlamentar', sa.String(), nullable=False),
    sa.Column('tipo_autoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_parlamentar'], ['parlamentares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pl'], ['pls_senado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pl', 'id_parlamentar')
    )
    op.create_table('tramitacao_camara',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pl', sa.Integer(), nullable=False),
    sa.Column('data_tramitacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('dados_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pl'], ['pls_camara.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tramitacao_senado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pl', sa.Integer(), nullable=False),
    sa.Column('data_tramitacao', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('dados_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pl'], ['pls_senado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tramitacao_senado')
    op.drop_table('tramitacao_camara')
    op.drop_table('autoria_senado')
    op.drop_table('autoria_camara')
    op.drop_table('pls_senado')
    op.drop_table('pls_camara')
    op.drop_table('parlamentares')
    # ### end Alembic commands ###
